### ISSUE TITLE
send_next() stops scheduling resends on second error

### ISSUE THREAD

**Issue by Artaud** [dillpixel/fitbit-asap#13]
Found a bug to squash!

In the send_next() method in both app and companion, when we get an error twice, there is no mechanism to schedule another send.
On first error, we schedule send in the send() method, but when we get an error even then, we just stop.

Pushing a fix

**Comment by Artaud** [comment]
I believe this should be fixed in https://github.com/dillpixel/fitbit-asap/commit/3d38adc7fc66dbbb899e00049d2e2480cf19ec75

Please review @daveyjones

**Comment by daveyjones** [comment]
Thanks! To keep things clean, should we just put `set_resend_timer()` once below the try/catch block?

**Comment by Artaud** [comment]
Ah, sure!

**Comment by Artaud** [comment]
I pushed it in a bunch of unnecessary commits...sorry for that, no idea how that happened and why are they empty...I just kept receiving prompts to auto merge with no diffs :)

**Comment by daveyjones** [comment]
No worries—thanks for the fix!
