### ISSUE TITLE
On dequeue, queue is completely emptied every time

### ISSUE THREAD

**Issue by Artaud** [dillpixel/fitbit-asap#14]
At https://github.com/dillpixel/fitbit-asap/blob/8a55e006f55d43fd5f0531943c1b3112240864e5/source/app.js#L37 and https://github.com/dillpixel/fitbit-asap/blob/8a55e006f55d43fd5f0531943c1b3112240864e5/source/companion.js#L37, the whole queue gets deleted most of the time, due to my embarassingly wrong use of Array.splice()

Fix incoming.

**Comment by Artaud** [comment]
Fixed in https://github.com/dillpixel/fitbit-asap/issues/14

**Comment by Artaud** [comment]
This would be probably a good time for a version bump as those fixes are quite critical, what do you think @daveyjones?

**Comment by daveyjones** [comment]
Done!
