### ISSUE TITLE
Callback for "message acked"

### ISSUE THREAD

**Issue by Artaud** [dillpixel/fitbit-asap#15]
I just found in my app that I needed to check that a certain message was indeed acked and then do something based on that event.
I wrote a callback for that for myself, should I add it to fitbit-asap as well?

**Comment by daveyjones** [comment]
Yes, that would be great. I was just thinking the other day that we need a callback after a message is received. The callback should be called even if the message is received after life cycle changes. I think the API should look like this:
```
asap.onreceipt = message => { ... }
```
The message could be passed to this function right before it's deleted from the queue.

**Comment by daveyjones** [comment]
I actually haven't run into any cases where this is needed. I'm going to close this for now, but feel free to comment if anyone else needs this.
